const constants = {
    PRODUCTS:{
        FETCH_PRODUCT_BY_ID : "FETCH_PRODUCT_BY_ID",
        FETCH_PRODUCTS_BY_CATEGORY_ID : "FETCH_PRODUCTS_BY_CATEGORY_ID",
        UPDATE_PRODUCTS_LIST : "UPDATE_PRODUCTS_LIST",

        ADD_NEW_PRODUCT : "ADD_NEW_PRODUCT",
        SET_BEFORE_DISCOUNT_PRICE : "SET_BEFORE_DISCOUNT_PRICE",
        SET_FINAL_PRICE : "SET_FINAL_PRICE",
        SET_COLOR : "SET_COLOR",
        DELETE_COLOR : "DELETE_COLOR",
        SET_DESCRIPTION : "SET_DESCRIPTION",
        SET_TAG : "SET_TAG",
        DELETE_TAG : "DELETE_TAG",
        ADD_COMMENT : "ADD_COMMENT",
        ADD_IMAGE : "ADD_IMAGE",
        DELETE_IMAGE : "DELETE_IMAGE",
        UPDATE_CATEGORY : "UPDATE_CATEGORY",
        GET_PRODUCT_BY_ID : "GET_PRODUCT_BY_ID",
        GET_PRODUCTS_BY_IDS : "GET_PRODUCTS_BY_IDS"
    },
    CATEGORY : {
        ADD_CATEGORY : "ADD_CATEGORY",
        DELETE_CATEGORY : "DELETE_CATEGORY",
        UPDATE_PARENT_ID : "UPDATE_PARENT_ID",
        UPDATE_NAME : "UPDATE_NAME",
        UPDATE_IMAGE : "UPDATE_NAME",
        FETCH_LIST_OF_CATEGORIES : "FETCH_LIST_OF_CATEGORIES",
        GET_CATEGORIES_BY_IDS : "GET_CATEGORIES_BY_IDS"
    },
    CART : {
        ADD_TO_CART : "ADD_TO_CART",
        IS_IN_CART : "IS_IN_CART",
        LOAD_ITEMS_IN_CART : "LOAD_ITEMS_IN_CART",
        CHANGE_NUMBER_OF_REQUESTED_UNITS : "CHANGE_NUMBER_OF_REQUESTED_UNITS",
        CALCULATE_SHIPPING_PRICE : "CALCULATE_SHIPPING_PRICE",
        CALCULATE_TAX : "CALCULATE_TAX",
        CALCULATE_ITEMS_PRICE :  "CALCULATE_ITEMS_PRICE",
        CALCULATE_FINAL_PRICE : "CALCULATE_FINAL_PRICE",
        CHOOSE_PAY_METHOD : "CHOOSE_PAY_METHOD",
        SET_ADDRESS : "SET_ADDRESS",
        CLEAR_CART : "CLEAR_CART",
        DELETE_ONE_FROM_CART : "DELETE_ONE_FROM_CART"
    },
    HOME_PAGE_COMPONENT : {
        FETCH_HOMEPAGE_COMPONENTS : "FETCH_HOMEPAGE_COMPONENTS"
    },
    STORE_SETTINGS :{
        IMAGES_URL : "http://gwf-demo.usask.ca/DummyServer/images/"
    }
}

export default constants